name: Cypress Tests

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug
        print_tags:
          description: "True to print to STDOUT"
          required: true
          type: boolean
        tags:
          description: "Test scenario tags"
          required: true
          type: string
        environment:
          description: "Environment to run tests against"
          type: environment
          required: true
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm start
  print-tag:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.print_tags == 'true' }}
    steps:
      - name: Print the input tag to STDOUT
        run: echo  The tags are ${{ github.event.inputs.tags }}
