name: Cypress Tests

on:
  workflow_dispatch:
    inputs:
      typeOfTest:
        description: "Tipo de teste a ser executado"
        required: true
        default: "regression"
        type: choice
        options:
          - regression
          - smoke
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm ${{ github.event.inputs.typeOfTest}}
